extends Node3D
# Ring scale vibe mock — issue #9. Standalone: open this scene, F6.
# Honest geometry: camera stands on the interior of a cylinder of radius R.
# Config keys: 1/2/3 circumference, Q/W/E width, Up/Down haze, T sun speed, P pause sun, F flip sun, R rebuild.

const CIRCUMFERENCES := [1_500_000.0, 2_097_152.0, 3_000_000.0]  # m (2^21 = substrate proposal)
const WIDTHS := [10_000.0, 32_768.0, 50_000.0]                    # m (2^15 = substrate proposal)
const SUN_PERIODS := [0.0, 1140.0, 60.0, 8.0]                     # s per full day: off, ~19min honest, fast, terminator-sweep
const STRIP_ARC := 100_000.0      # near-field strip: +/- this many meters of arc
const STRIP_SEGS := 320
const STRIP_ROWS := 80
const BAND_SEGS := 1024
const BAND_ROWS := 8
const WALL_HEIGHT := 3_000.0
const WALL_RAMP := 2_500.0        # lat meters over which wall rises
const RIDGE_ARC := 50_000.0       # money-shot ridge distance spinward
const RIDGE_AMP := 1_500.0
const NOISE_AMP := 1_100.0

var c_idx := 2   # locked 2026-07-23: widest circumference (3,000 km)
var w_idx := 2   # locked 2026-07-23: widest width (50 km)
var haze_density := 0.000008      # 1/m — ~125km extinction default (Up/Dn tunes)
var sun_speed_idx := 1
var sun_angle := 0.35             # radians around ring plane; 0 = noon at camera
var sun_paused := false

var _cam: Camera3D
var _hud: Label
var _mat: ShaderMaterial
var _band: MeshInstance3D
var _strips: Array[MeshInstance3D] = []
var _noise := FastNoiseLite.new()
var _look := Vector2.ZERO
var _captured := false
var _env: Environment
var _sun: DirectionalLight3D = null

# Real-DEM near terrain (splice_dem prototype) — generated by tools/dem/export_to_game.py, gitignored
const DEM_R16 := "res://mocks/dem/millstreet.r16"
const DEM_META := "res://mocks/dem/millstreet.json"
const DEM_DETAIL := "res://mocks/dem/millstreet_detail.dat"
const DEM_SAT := "res://mocks/dem/millstreet_sat.dat"
const DEM_ROADS := "res://mocks/dem/millstreet_roads.dat"
var _dem := PackedByteArray()
var _dem_w := 0
var _dem_h := 0
var _dem_mpp := 23.45
var _dem_cam := Vector2i.ZERO
var _dem_name := ""
var _detail_tex: ImageTexture = null
var _sat_tex: ImageTexture = null
var _roads_tex: ImageTexture = null
var _strip_mat: ShaderMaterial = null

enum Mode { FLY, DRIVE, WALK }
var _mode: Mode = Mode.FLY
const WALK_SPEED := 10.0   # reused from game/player.gd's SPEED for consistency with the real game
const WALK_RUN_MULT := 2.0
const EYE_HEIGHT := 1.7
var _walk_arc := 0.0       # walk tracked in ring arc/lat like the car (fixes curve-mismatch clipping)
var _walk_lat := 0.0

# Drive mode: car lives in ring coordinates, no physics — terrain sampled analytically
var _car: Node3D = null
var _car_arc := 0.0
var _car_lat := 0.0
var _car_heading := 0.0
var _car_speed := 0.0
var _hud_timer := 0.0
var dem_scale := 1.0  # locked 2026-07-23: lowest/no exaggeration
var _strip_arc := STRIP_ARC
var _strip_segs := STRIP_SEGS
var _strip_rows := STRIP_ROWS

# First-slice creature test (slice-mock.md) — generic startle/flee proxy, deer + wolf presets
const CreatureScript := preload("res://mocks/creature.gd")
var _creatures: Array = []
var _threat_active := false
var _trees: MultiMeshInstance3D = null
var _forest_noise := FastNoiseLite.new()
var _walls: Array[MeshInstance3D] = []
const WALL_ARC := 42_000.0   # walls built over the visible near arc; beyond is hazed

func _ready() -> void:
	_noise.noise_type = FastNoiseLite.TYPE_SIMPLEX
	_noise.fractal_octaves = 4
	_noise.frequency = 1.0 / 9_000.0
	_load_dem()

	_cam = Camera3D.new()
	_cam.position = Vector3(0, 120, 0)
	_cam.near = 0.5
	_cam.far = 3_000_000.0
	add_child(_cam)
	_cam.make_current()

	_env = Environment.new()
	_env.background_mode = Environment.BG_COLOR
	_env.background_color = Color(0.45, 0.62, 0.82)
	_env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	_env.ambient_light_color = Color(0.5, 0.6, 0.72)
	_env.ambient_light_energy = 0.4
	var we := WorldEnvironment.new()
	we.environment = _env
	add_child(we)

	# sun light for StandardMaterial3D objects (trees, car, creatures) — terrain keeps its
	# own manual in-shader lighting; this just makes the real-material props shade to match.
	_sun = DirectionalLight3D.new()
	_sun.light_energy = 1.1
	add_child(_sun)

	var shader := load("res://mocks/ring_vibes.gdshader") as Shader
	_mat = ShaderMaterial.new()
	_mat.shader = shader
	_mat.set_shader_parameter("city_tex", _make_city_texture())
	if _detail_tex:
		_strip_mat = ShaderMaterial.new()
		_strip_mat.shader = load("res://mocks/ring_vibes_strip.gdshader") as Shader
		_strip_mat.set_shader_parameter("detail_tex", _detail_tex)
		if _sat_tex:
			_strip_mat.set_shader_parameter("sat_tex", _sat_tex)
			_strip_mat.set_shader_parameter("has_sat", true)
		if _roads_tex:
			_strip_mat.set_shader_parameter("road_tex", _roads_tex)
			_strip_mat.set_shader_parameter("has_roads", true)

	var hud_layer := CanvasLayer.new()
	add_child(hud_layer)
	_hud = Label.new()
	_hud.position = Vector2(12, 12)
	_hud.add_theme_color_override("font_color", Color(1, 1, 1, 0.9))
	_hud.add_theme_constant_override("outline_size", 4)
	_hud.add_theme_color_override("font_outline_color", Color(0, 0, 0, 0.8))
	hud_layer.add_child(_hud)

	_rebuild()
	if _dem_w > 0:
		_cam.position.y = _terrain_h(0.0, 0.0, WIDTHS[w_idx]) + 40.0  # spawn just above Millstreet

func _radius() -> float:
	return CIRCUMFERENCES[c_idx] / TAU

# Ring-space to local: theta=0 under camera, floor y=0, spinward = +x, lat = z.
func _ring_pos(theta: float, lat: float, h: float) -> Vector3:
	var r: float = _radius() - h
	return Vector3(r * sin(theta), _radius() - r * cos(theta), lat)

func _load_dem() -> void:
	if not FileAccess.file_exists(DEM_R16) or not FileAccess.file_exists(DEM_META):
		print("ring_vibes: no DEM found (run tools/dem/fetch_dem.py then export_to_game.py) — using noise terrain")
		return
	var meta: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(DEM_META))
	_dem = FileAccess.get_file_as_bytes(DEM_R16)
	_dem_w = int(meta["w"])
	_dem_h = int(meta["h"])
	_dem_mpp = float(meta["m_per_px"])
	_dem_cam = Vector2i(int(meta["camera_px"][0]), int(meta["camera_px"][1]))
	_dem_name = str(meta["name"])
	if FileAccess.file_exists(DEM_DETAIL):
		var img := Image.new()
		if img.load_png_from_buffer(FileAccess.get_file_as_bytes(DEM_DETAIL)) == OK:
			img.generate_mipmaps()
			_detail_tex = ImageTexture.create_from_image(img)
	if FileAccess.file_exists(DEM_SAT):
		var simg := Image.new()
		if simg.load_png_from_buffer(FileAccess.get_file_as_bytes(DEM_SAT)) == OK:
			simg.generate_mipmaps()
			_sat_tex = ImageTexture.create_from_image(simg)
	if FileAccess.file_exists(DEM_ROADS):
		var rimg := Image.new()
		if rimg.load_png_from_buffer(FileAccess.get_file_as_bytes(DEM_ROADS)) == OK:
			rimg.generate_mipmaps()
			_roads_tex = ImageTexture.create_from_image(rimg)
	print("ring_vibes: DEM loaded — ", _dem_name, " ", _dem_w, "x", _dem_h,
		"  detail_tex: ", "yes" if _detail_tex else "no",
		"  sat_tex: ", "yes" if _sat_tex else "no")

func _dem_sample(arc: float, lat: float) -> float:
	# arc -> east (+px x), lat -> north (-px y), anchored at the Millstreet marker; bilinear; -1 = outside
	var fx: float = float(_dem_cam.x) + arc / _dem_mpp
	var fy: float = float(_dem_cam.y) - lat / _dem_mpp
	if fx < 1.0 or fy < 1.0 or fx >= float(_dem_w) - 2.0 or fy >= float(_dem_h) - 2.0:
		return -1.0
	var x0 := int(fx); var y0 := int(fy)
	var tx: float = fx - float(x0); var ty: float = fy - float(y0)
	var h00 := float(_dem.decode_u16((y0 * _dem_w + x0) * 2)) / 16.0
	var h10 := float(_dem.decode_u16((y0 * _dem_w + x0 + 1) * 2)) / 16.0
	var h01 := float(_dem.decode_u16(((y0 + 1) * _dem_w + x0) * 2)) / 16.0
	var h11 := float(_dem.decode_u16(((y0 + 1) * _dem_w + x0 + 1) * 2)) / 16.0
	return lerpf(lerpf(h00, h10, tx), lerpf(h01, h11, tx), ty)

func _terrain_h(arc: float, lat: float, w: float) -> float:
	# floor only — the wall is a separate vertical structure (_build_walls), no longer a ramp
	# added onto the terrain (which was walkable and phased through itself at the seams).
	if _dem_w > 0:
		var dh: float = _dem_sample(arc, lat)
		if dh >= 0.0:
			# runtime detail octave (the bake architecture's plan, prototyped): sub-mesh-res relief
			var detail: float = _noise.get_noise_2d(arc * 3.0, lat * 3.0) * 16.0
			return dh * dem_scale + detail
		return 0.0  # outside coverage: flat
	# noise fallback (original mock terrain)
	var feather: float = clampf(1.0 - abs(arc) / _strip_arc, 0.0, 1.0)
	var h: float = maxf(_noise.get_noise_2d(arc, lat), 0.0) * NOISE_AMP * smoothstep(0.0, 0.15, feather)
	var ridge_d: float = (arc - RIDGE_ARC) / 9_000.0
	h += RIDGE_AMP * exp(-ridge_d * ridge_d) * feather
	return h

func _rebuild() -> void:
	if _band: _band.queue_free()
	for s in _strips: s.queue_free()
	_strips.clear()
	var w: float = WIDTHS[w_idx]
	var r: float = _radius()

	# Far band: whole ring, flat, sunk 80m so the strip covers it near the camera
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for i in BAND_SEGS + 1:
		var theta: float = TAU * float(i) / float(BAND_SEGS)
		for j in BAND_ROWS + 1:
			var lat: float = w * (float(j) / float(BAND_ROWS) - 0.5)
			st.set_uv(Vector2(float(i) / float(BAND_SEGS), float(j) / float(BAND_ROWS)))
			st.add_vertex(_ring_pos(theta, lat, -80.0))
	_grid_indices(st, BAND_SEGS, BAND_ROWS)
	st.generate_normals()
	_band = MeshInstance3D.new()
	_band.mesh = st.commit()
	_band.material_override = _mat
	add_child(_band)

	# Near strip: two-tier real DEM when present (dense inner, coarse outer), else noise mountains
	if _dem_w > 0:
		_strip_arc = 42_000.0
		_strips.append(_build_strip(42_000.0, 255, 100, -3.0, w, r))   # outer, sunk under inner
		_strips.append(_build_strip(12_000.0, 220, 300, 0.5, w, r))    # inner, ~110 m mesh
	else:
		_strip_arc = STRIP_ARC
		_strips.append(_build_strip(STRIP_ARC, STRIP_SEGS, STRIP_ROWS, 0.0, w, r))
	_build_walls()
	_scatter_trees()
	_update_hud()

func _build_walls() -> void:
	# dedicated vertical rim walls at lat = +/- w/2: clean impassable structure, not a ramp.
	# Terrain (floor-only now) meets the wall base; walk mode already clamps lat inside it.
	for m in _walls:
		m.queue_free()
	_walls.clear()
	var w: float = WIDTHS[w_idx]
	var r: float = _radius()
	var segs := 400
	for side in [-1.0, 1.0]:
		var lat: float = side * w * 0.5
		var st := SurfaceTool.new()
		st.begin(Mesh.PRIMITIVE_TRIANGLES)
		for i in segs + 1:
			var arc: float = WALL_ARC * (2.0 * float(i) / float(segs) - 1.0)
			var theta: float = arc / r
			var base: float = _terrain_h(arc, lat, w) - 30.0  # dip below floor, no gap
			st.set_uv(Vector2(float(i) / float(segs), 1.0))
			st.add_vertex(_ring_pos(theta, lat, base))
			st.set_uv(Vector2(float(i) / float(segs), 0.0))
			st.add_vertex(_ring_pos(theta, lat, base + WALL_HEIGHT))
		for i in segs:
			var a := i * 2
			st.add_index(a); st.add_index(a + 2); st.add_index(a + 1)
			st.add_index(a + 1); st.add_index(a + 2); st.add_index(a + 3)
		st.generate_normals()
		var mi := MeshInstance3D.new()
		mi.mesh = st.commit()
		var wm := StandardMaterial3D.new()
		wm.albedo_color = Color(0.58, 0.60, 0.64)
		wm.roughness = 0.9
		wm.cull_mode = BaseMaterial3D.CULL_DISABLED
		mi.material_override = wm
		add_child(mi)
		_walls.append(mi)

func _build_strip(arc_ext: float, segs: int, rows: int, h_off: float, w: float, r: float) -> MeshInstance3D:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for i in segs + 1:
		var arc: float = arc_ext * (2.0 * float(i) / float(segs) - 1.0)
		for j in rows + 1:
			var lat: float = w * (float(j) / float(rows) - 0.5)
			if _dem_w > 0:
				var fx: float = (float(_dem_cam.x) + arc / _dem_mpp) / float(_dem_w)
				var fy: float = (float(_dem_cam.y) - lat / _dem_mpp) / float(_dem_h)
				st.set_uv(Vector2(clampf(fx, 0.0, 1.0), clampf(fy, 0.0, 1.0)))
			else:
				st.set_uv(Vector2(0.001, 0.5))  # off the city texture clusters
			st.add_vertex(_ring_pos(arc / r, lat, _terrain_h(arc, lat, w) + h_off))
	_grid_indices(st, segs, rows)
	st.generate_normals()
	var mi := MeshInstance3D.new()
	mi.mesh = st.commit()
	mi.material_override = _strip_mat if (_dem_w > 0 and _strip_mat) else _mat
	add_child(mi)
	return mi

func _grid_indices(st: SurfaceTool, segs: int, rows: int) -> void:
	# 2026-07-23: attempted a winding flip + cull_back here, got the direction wrong (rendered
	# almost nothing). Reverted to the original order + cull_disabled (double-sided, known-working)
	# rather than guess again. Walk mode (ground-snapped) is the real fix for "finding the floor."
	for i in segs:
		for j in rows:
			var a: int = i * (rows + 1) + j
			var b: int = a + rows + 1
			st.add_index(a); st.add_index(b); st.add_index(a + 1)
			st.add_index(a + 1); st.add_index(b); st.add_index(b + 1)

func _make_city_texture() -> ImageTexture:
	var img := Image.create_empty(2048, 64, false, Image.FORMAT_RGB8)
	var rng := RandomNumberGenerator.new()
	rng.seed = 7
	for c in 70:
		var cx := rng.randi_range(64, 2047)  # keep lon~0 (camera region) wilderness
		var cy := rng.randi_range(8, 55)
		var n := rng.randi_range(40, 260)
		var spread := rng.randf_range(3.0, 14.0)
		for p in n:
			var px := clampi(cx + int(rng.randfn(0.0, spread)), 0, 2047)
			var py := clampi(cy + int(rng.randfn(0.0, spread * 0.35)), 0, 63)
			var warm := rng.randf_range(0.75, 1.0)
			img.set_pixel(px, py, Color(warm, warm * 0.82, warm * 0.5))
	return ImageTexture.create_from_image(img)

func _process(delta: float) -> void:
	var period: float = SUN_PERIODS[sun_speed_idx]
	if period > 0.0 and not sun_paused:
		sun_angle = fmod(sun_angle + TAU * delta / period, TAU)
	var to_sun := Vector3(sin(sun_angle), cos(sun_angle), 0)
	_mat.set_shader_parameter("to_sun", to_sun)
	_mat.set_shader_parameter("haze_density", haze_density)
	_mat.set_shader_parameter("ring_width", WIDTHS[w_idx])
	_mat.set_shader_parameter("wall_ramp", WALL_RAMP)
	if _sun:
		_sun.rotation = Vector3(-asin(clampf(to_sun.y, -1.0, 1.0)), 0.0, 0.0)
		_sun.light_energy = clampf(to_sun.y, 0.0, 1.0) * 1.1
		_sun.light_color = Color(1.0, 0.95, 0.86)
	if _strip_mat:
		_strip_mat.set_shader_parameter("to_sun", to_sun)
		_strip_mat.set_shader_parameter("haze_density", haze_density)
		_strip_mat.set_shader_parameter("dem_scale", dem_scale)
		_strip_mat.set_shader_parameter("ring_width", WIDTHS[w_idx])
		_strip_mat.set_shader_parameter("wall_ramp", WALL_RAMP)
	# camera-local day factor drives the sky color
	var day: float = clampf(to_sun.y, 0.0, 1.0)
	var sky := Color(0.45, 0.62, 0.82).lerp(Color(0.015, 0.02, 0.05), 1.0 - day)
	_env.background_color = sky
	_mat.set_shader_parameter("sky_color", Vector3(sky.r, sky.g, sky.b))
	if _strip_mat:
		_strip_mat.set_shader_parameter("sky_color", Vector3(sky.r, sky.g, sky.b))
	match _mode:
		Mode.DRIVE: _drive_tick(delta)
		Mode.WALK: _walk_tick(delta)
		_: _fly(delta)

const TREE_MODEL := "res://low_poly_red_spruce_tree_custom_textures/low_poly_red_spruce_tree_custom_textures/scene.gltf"
const FOREST_HALF := 700.0   # patch half-extent around spawn, in BOTH arc and lat (was full 50km width!)

func _find_first_mesh(node: Node) -> Mesh:
	if node is MeshInstance3D and node.mesh:
		return node.mesh
	for child in node.get_children():
		var m := _find_first_mesh(child)
		if m:
			return m
	return null

func _tree_mesh() -> Mesh:
	# real low-poly spruce (gitignored, local-only like the DEM) with a cone fallback
	if ResourceLoader.exists(TREE_MODEL):
		var packed := load(TREE_MODEL) as PackedScene
		if packed:
			var inst := packed.instantiate()
			var m := _find_first_mesh(inst)
			inst.queue_free()
			if m:
				return m
	var cone := CylinderMesh.new()
	cone.top_radius = 0.02; cone.bottom_radius = 1.7; cone.height = 5.0
	var tm := StandardMaterial3D.new()
	tm.albedo_color = Color(0.16, 0.24, 0.13)
	cone.material = tm
	return cone

func _scatter_trees() -> void:
	# conifers clumped by noise into woods + clearings, on the curved surface, in a PATCH
	# near spawn (not a ring-spanning carpet). Cover for the wolves moment; the deer clearing.
	if _dem_w == 0:
		return
	if _trees:
		_trees.queue_free()
	_forest_noise.noise_type = FastNoiseLite.TYPE_SIMPLEX
	_forest_noise.frequency = 1.0 / 300.0
	var mesh := _tree_mesh()
	var real_model := not (mesh is CylinderMesh)  # cone fallback is a CylinderMesh
	# scale: real gltf spruce imports small/large unpredictably; normalize to ~8m tall via aabb
	var aabb := mesh.get_aabb()
	var base_scale: float = (8.0 / maxf(aabb.size.y, 0.01)) if real_model else 1.0
	var mm := MultiMesh.new()
	mm.transform_format = MultiMesh.TRANSFORM_3D
	mm.mesh = mesh
	var xf: Array[Transform3D] = []
	var w: float = WIDTHS[w_idx]
	var r: float = _radius()
	var lat_lo: float = maxf(-FOREST_HALF, -w * 0.5 + 120.0)
	var lat_hi: float = minf(FOREST_HALF, w * 0.5 - 120.0)
	var rng := RandomNumberGenerator.new()
	rng.seed = 1234
	var arc := -FOREST_HALF
	while arc <= FOREST_HALF:
		var lat := lat_lo
		while lat <= lat_hi:
			var jx: float = arc + rng.randf_range(-12, 12)
			var jz: float = lat + rng.randf_range(-12, 12)
			if _forest_noise.get_noise_2d(jx, jz) > 0.12 and rng.randf() < 0.6:
				var h: float = _terrain_h(jx, jz, w)
				var pos := _ring_pos(jx / r, jz, h)
				var up := _ring_up(pos)
				var sc: float = base_scale * rng.randf_range(0.75, 1.4)
				var basis := Basis()
				basis.y = up
				basis.x = up.cross(Vector3.FORWARD).normalized()
				basis.z = basis.x.cross(up).normalized()
				basis = basis.rotated(up, rng.randf() * TAU).scaled(Vector3(sc, sc, sc))
				xf.append(Transform3D(basis, pos))
			lat += 22.0
		arc += 22.0
	mm.instance_count = xf.size()
	for i in xf.size():
		mm.set_instance_transform(i, xf[i])
	_trees = MultiMeshInstance3D.new()
	_trees.multimesh = mm
	add_child(_trees)
	print("ring_vibes: scattered ", xf.size(), " trees (", "real model" if real_model else "cone fallback", ") in ", int(FOREST_HALF * 2), "m patch")

func _terrain_height_flat(x: float, z: float) -> float:
	# creature-space height: walk-mode approximation treats world x/z as arc/lat directly
	return _terrain_h(x, z, WIDTHS[w_idx])

func _player_pos() -> Vector3:
	return _cam.global_position

func _spawn_creatures(preset: String, n: int, dist: float) -> void:
	if _dem_w == 0:
		return
	var base := _cam.global_position
	var fwd := -_cam.global_basis.z
	fwd.y = 0.0
	fwd = fwd.normalized()
	# deer ahead (+dist along view), wolves behind (-dist); scatter around that point
	var center := base + fwd * (dist if preset == "deer" else -dist)
	for i in n:
		var c = CreatureScript.new()
		c.configure(preset)
		c.height_fn = _terrain_height_flat
		c.threat_fn = _player_pos
		if preset == "wolf":
			c.became_threat.connect(_on_threat)
		add_child(c)
		var off := Vector3(randf_range(-25, 25), 0, randf_range(-25, 25))
		var p := center + off
		p.y = _terrain_height_flat(p.x, p.z)
		c.global_position = p
		_creatures.append(c)
	_update_hud()

func _clear_creatures() -> void:
	for c in _creatures:
		if is_instance_valid(c):
			c.queue_free()
	_creatures.clear()
	_threat_active = false
	_update_hud()

func _on_threat(active: bool) -> void:
	# null-write test surface: deer must NEVER reach here; only a wolf in APPROACH does
	_threat_active = active
	_update_hud()

func _make_car() -> Node3D:
	var root := Node3D.new()
	var body := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = Vector3(2.0, 1.0, 4.2)
	body.mesh = bm
	var bmat := StandardMaterial3D.new()
	bmat.albedo_color = Color(0.33, 0.36, 0.30)
	body.material_override = bmat
	body.position.y = 0.9
	root.add_child(body)
	var glass := MeshInstance3D.new()
	var gm := BoxMesh.new()
	gm.size = Vector3(1.7, 0.5, 1.1)
	glass.mesh = gm
	var gmat := StandardMaterial3D.new()
	gmat.albedo_color = Color(0.45, 0.75, 0.80)  # frutiger windscreen, obviously
	glass.material_override = gmat
	glass.position = Vector3(0, 1.55, -0.5)
	root.add_child(glass)
	var wmat := StandardMaterial3D.new()
	wmat.albedo_color = Color(0.10, 0.10, 0.10)
	for wp in [Vector3(-1.05, 0.45, 1.4), Vector3(1.05, 0.45, 1.4), Vector3(-1.05, 0.45, -1.4), Vector3(1.05, 0.45, -1.4)]:
		var wheel := MeshInstance3D.new()
		var cm := CylinderMesh.new()
		cm.height = 0.35
		cm.top_radius = 0.45
		cm.bottom_radius = 0.45
		wheel.mesh = cm
		wheel.rotation_degrees = Vector3(0, 0, 90)
		wheel.position = wp
		wheel.material_override = wmat
		root.add_child(wheel)
	add_child(root)
	return root

func _car_pos(arc: float, lat: float) -> Vector3:
	return _ring_pos(arc / _radius(), lat, _terrain_h(arc, lat, WIDTHS[w_idx]))

# local up at a ring surface point = toward the cylinder axis (0, R, lat/z)
func _ring_up(pos: Vector3) -> Vector3:
	return (Vector3(0.0, _radius(), pos.z) - pos).normalized()

func _drive_tick(delta: float) -> void:
	var accel := 0.0
	if Input.is_key_pressed(KEY_W): accel += 9.0
	if Input.is_key_pressed(KEY_S): accel -= 12.0
	_car_speed = clampf(_car_speed + accel * delta, -6.0, 22.0)  # ~80 km/h top (was 160)
	_car_speed *= 1.0 - 0.35 * delta  # drag
	var steer := 0.0
	if Input.is_key_pressed(KEY_A): steer -= 1.0
	if Input.is_key_pressed(KEY_D): steer += 1.0
	_car_heading += steer * 1.5 * delta * clampf(abs(_car_speed) / 12.0, 0.0, 1.0) * signf(_car_speed)
	_car_arc += cos(_car_heading) * _car_speed * delta
	_car_lat += sin(_car_heading) * _car_speed * delta
	var pos := _car_pos(_car_arc, _car_lat)
	var ahead := _car_pos(_car_arc + cos(_car_heading) * 5.0, _car_lat + sin(_car_heading) * 5.0)
	var up := _ring_up(pos)
	_car.global_position = pos + up * 0.4
	if not pos.is_equal_approx(ahead):
		_car.look_at(ahead + up * 0.4, up)
	var fwd := (ahead - pos).normalized()
	var cam_target: Vector3 = pos + up * 4.0 - fwd * 11.0
	_cam.position = _cam.position.lerp(cam_target, 1.0 - exp(-5.0 * delta))
	_cam.look_at(pos + up * 2.0, up)
	_hud_timer += delta
	if _hud_timer > 0.25:
		_hud_timer = 0.0
		_update_hud()

func _walk_tick(delta: float) -> void:
	var speed: float = WALK_SPEED * (WALK_RUN_MULT if Input.is_key_pressed(KEY_SHIFT) else 1.0)
	var f := 0.0  # forward/back
	var s := 0.0  # strafe
	if Input.is_key_pressed(KEY_W): f += 1.0
	if Input.is_key_pressed(KEY_S): f -= 1.0
	if Input.is_key_pressed(KEY_D): s += 1.0
	if Input.is_key_pressed(KEY_A): s -= 1.0
	var mv := Vector2(s, f)
	if mv != Vector2.ZERO:
		mv = mv.normalized()
	var yaw: float = _look.x
	# camera-relative in arc(=x-like)/lat(=z-like) space. yaw=0 faces +arc-ish.
	# forward = -Z of the camera basis projected to the ground plane.
	# camera forward (-Z) at yaw = (-sin, -cos) in (arc,lat); right (+X) = (cos, -sin)
	var d_arc := (-mv.y * sin(yaw) + mv.x * cos(yaw)) * speed * delta
	var d_lat := (-mv.y * cos(yaw) - mv.x * sin(yaw)) * speed * delta
	var w: float = WIDTHS[w_idx]
	_walk_arc += d_arc
	_walk_lat = clampf(_walk_lat + d_lat, -w * 0.5 + 50.0, w * 0.5 - 50.0)
	var ground := _ring_pos(_walk_arc / _radius(), _walk_lat, _terrain_h(_walk_arc, _walk_lat, w))
	_cam.position = ground + _ring_up(ground) * EYE_HEIGHT
	_cam.rotation = Vector3(_look.y, _look.x, 0)

func _set_mode(m: Mode) -> void:
	_mode = m
	if m == Mode.DRIVE:
		if not _car:
			_car = _make_car()
		_car.visible = true
		_car_speed = 0.0
		Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
		_captured = false
	else:
		if _car:
			_car.visible = false
		if m == Mode.WALK:
			var w: float = WIDTHS[w_idx]
			# init arc/lat from current camera (near origin worldx≈arc), then snap to curved surface
			_walk_arc = _cam.position.x
			_walk_lat = clampf(_cam.position.z, -w * 0.5 + 50.0, w * 0.5 - 50.0)
			var ground := _ring_pos(_walk_arc / _radius(), _walk_lat, _terrain_h(_walk_arc, _walk_lat, w))
			_cam.position = ground + _ring_up(ground) * EYE_HEIGHT
		_cam.rotation = Vector3(_look.y, _look.x, 0)
	_update_hud()

func _fly(delta: float) -> void:
	# fly only while mouse captured; config keys only while released — no key conflicts
	if not _captured: return
	var speed: float = 800.0 if Input.is_key_pressed(KEY_SHIFT) else 60.0
	var dir := Vector3.ZERO
	if Input.is_key_pressed(KEY_W): dir -= _cam.global_basis.z
	if Input.is_key_pressed(KEY_S): dir += _cam.global_basis.z
	if Input.is_key_pressed(KEY_A): dir -= _cam.global_basis.x
	if Input.is_key_pressed(KEY_D): dir += _cam.global_basis.x
	if Input.is_key_pressed(KEY_SPACE): dir += Vector3.UP
	if Input.is_key_pressed(KEY_CTRL): dir -= Vector3.UP
	if dir != Vector3.ZERO:
		_cam.position += dir.normalized() * speed * delta

func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.pressed and not _captured:
		Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
		_captured = true
		_update_hud()
	if event is InputEventMouseMotion and _captured and _mode != Mode.DRIVE:
		_look -= event.relative * 0.0022
		_look.y = clampf(_look.y, -1.55, 1.55)
		_cam.rotation = Vector3(_look.y, _look.x, 0)
	if event is InputEventKey and event.pressed:
		if event.keycode == KEY_ESCAPE:
			Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
			_captured = false
			_update_hud()
			return
		# always-available keys
		match event.keycode:
			KEY_UP: haze_density *= 1.5; _update_hud()
			KEY_DOWN: haze_density /= 1.5; _update_hud()
			KEY_T: sun_speed_idx = (sun_speed_idx + 1) % SUN_PERIODS.size(); _update_hud()
			KEY_P: sun_paused = not sun_paused
			KEY_F: sun_angle = fmod(sun_angle + PI, TAU)
			KEY_R: _rebuild()
			KEY_K: _spawn_creatures("deer", 6, 60.0)   # herd ahead
			KEY_J: _spawn_creatures("wolf", 3, 90.0)    # pack behind
			KEY_C: _clear_creatures()
			KEY_H:
				if _dem_w > 0:
					dem_scale = 1.0 if dem_scale >= 5.0 else dem_scale + 1.0
					_rebuild()
			KEY_V:
				if _dem_w > 0:
					var order := [Mode.FLY, Mode.DRIVE, Mode.WALK]
					_set_mode(order[(order.find(_mode) + 1) % 3])
		if _captured or _mode == Mode.DRIVE: return
		# config keys only while mouse is released
		match event.keycode:
			KEY_1: c_idx = 0; _rebuild()
			KEY_2: c_idx = 1; _rebuild()
			KEY_3: c_idx = 2; _rebuild()
			KEY_Q: w_idx = 0; _rebuild()
			KEY_W: w_idx = 1; _rebuild()
			KEY_E: w_idx = 2; _rebuild()

func _update_hud() -> void:
	var c: float = CIRCUMFERENCES[c_idx]
	var w: float = WIDTHS[w_idx]
	var r: float = _radius()
	var rise20: float = 20_000.0 * 20_000.0 / (2.0 * r)
	var rise50: float = 50_000.0 * 50_000.0 / (2.0 * r)
	var band_deg: float = rad_to_deg(2.0 * atan((w * 0.5) / (2.0 * r)))
	var mode := "FLY (WASD + Space/Ctrl, Shift boost, ESC to release, [V] cycle mode)" if _captured else "CONFIG ([1/2/3] circ  [Q/W/E] width — click to fly, [V] cycle drive/walk)"
	if _mode == Mode.DRIVE:
		mode = "DRIVE  %d km/h  (WASD steer, [V] cycle mode)" % int(abs(_car_speed) * 3.6)
	elif _mode == Mode.WALK:
		mode = "WALK  (WASD + mouse-look, Shift run, ESC release, [V] cycle mode)"
	var dem_line := "DEM: none (noise terrain)" if _dem_w == 0 else "DEM: %s   height x%.0f ([H] cycles)" % [_dem_name, dem_scale]
	# note: GDScript has no %e — haze shown as extinction distance instead (nicer to reason about anyway)
	var haze_km: float = 1.0 / maxf(haze_density, 1e-9) / 1000.0
	# creature/slice test line: threat state is the null-write acceptance test surface —
	# deer must keep it OFF no matter how close you get; only a wolf in APPROACH turns it ON.
	var threat := "THREAT (wolf closing)" if _threat_active else "calm (null-write holding)"
	var slice_line := "[K] deer herd  [J] wolf pack  [C] clear   creatures: %d   %s" % [_creatures.size(), threat]
	_hud.text = "C = %.0f km   W = %.1f km   R = %.1f km\nrise @20km = %.0f m   @50km = %.0f m   far-side band = %.2f deg (moon = 0.52)\nhaze extinction ~%.0f km   sun period = %s s\n%s\n%s\n[Up/Dn] haze  [T] sun speed  [P] pause sun  [F] flip day/night  [R] rebuild\nmode: %s" % [
		c / 1000.0, w / 1000.0, r / 1000.0, rise20, rise50, band_deg, haze_km,
		("off" if SUN_PERIODS[sun_speed_idx] == 0.0 else str(SUN_PERIODS[sun_speed_idx])), dem_line, slice_line, mode]
